package ica.oose.padel.backend.persistence;

import java.io.Serializable;
import java.util.Objects;

public class FieldId implements Serializable {

    private String name;
    private String clubName;

    public FieldId() {}

    public FieldId(String name, String clubName) {
        this.name = name;
        this.clubName = clubName;
    }

    //This method checks to make sure that the obj argument is not null and that it references an instance of the same type as this object.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FieldId fieldId = (FieldId) o;
        return Objects.equals(name, fieldId.name) && Objects.equals(clubName, fieldId.clubName);
    }

    //This method returns an integer value, generated by a hashing algorithm. Objects that are equal (according to their equals()) must return the same hash code.
    @Override
    public int hashCode() {
        return Objects.hash(name, clubName);
    }

}