package ica.oose.padel.backend.persistence;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class InviteId implements Serializable {

    private String gameDate;
    private String gameClubName;
    private String gameField;
    private String invitee;

    public InviteId() {}

    public InviteId(String gameDate, String gameClubName, String gameField, String invitee) {
        this.gameDate = gameDate;
        this.gameClubName = gameClubName;
        this.gameField = gameField;
        this.invitee = invitee;
    }

    //This method checks to make sure that the obj argument is not null and that it references an instance of the same type as this object.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        InviteId inviteId = (InviteId) o;
        return Objects.equals(gameDate, inviteId.gameDate) && Objects.equals(gameClubName, inviteId.gameClubName) && Objects.equals(gameField, inviteId.gameField) && Objects.equals(invitee, inviteId.invitee);
    }

    //This method returns an integer value, generated by a hashing algorithm. Objects that are equal (according to their equals()) must return the same hash code.
    @Override
    public int hashCode() {
        return Objects.hash(gameDate, gameClubName, gameField, invitee);
    }

}
