package ica.oose.padel.backend.persistence;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class GameId implements Serializable {

    private Date date;
    private String clubName;
    private String field;

    public GameId() {}

    public GameId(Date date, String clubName, String field) {
        this.date = date;
        this.clubName = clubName;
        this.field = field;
    }

    //This method checks to make sure that the obj argument is not null and that it references an instance of the same type as this object.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GameId gameId = (GameId) o;
        return Objects.equals(date, gameId.date) && Objects.equals(clubName, gameId.clubName) && Objects.equals(field, gameId.field);
    }

    //This method returns an integer value, generated by a hashing algorithm. Objects that are equal (according to their equals()) must return the same hash code.
    @Override
    public int hashCode() {
        return Objects.hash(date, clubName, field);
    }

}